target-version = "py310"

[lint]
select = ["E", "W", "F", "B", "I", "UP", "N", "PL", "RUF"]
ignore = []

# Code complexity threshold
mccabe = { max-complexity = 7 }

[lint.pylint]
max-args = 5
max-returns = 3
max-statements = 25
